spring.application.name=swipes
server.port=8095
server.servlet.context-path=/email
# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/tinder
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true