spring.application.name=preferencias
server.port=8094
server.servlet.context-path=/preferencias
# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/tinder
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true